<?php
/**
 * Gutenverse About Fun Fact content.
 */
return array(
	'title'      => __( 'Gutenverse About Fun Fact', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-85aBzC","margin":{"Desktop":[],"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"80","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"40","top":"20"}},"Tablet":[]}} -->
			<div class="section-wrapper" data-id="85aBzC"><script>var top85aBzC = {"Desktop":{"point":"0","unit":"px"}};var bottom85aBzC = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-85aBzC layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":null,"Tablet":null},"elementId":"guten-MgVNAM","margin":{"Desktop":{"unit":"px","dimension":{"left":"0","right":"20","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"30","right":"0","left":"0","top":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-MgVNAM"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="MgVNAM"><script>var topMgVNAM = {"Desktop":{"point":"0","unit":"px"}};var bottomMgVNAM = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-QSrQgk","icon":"gtn gtn-stats-light","iconColor":{"Desktop":{"r":233,"g":143,"b":80,"a":1}},"iconBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"iconSize":{"Desktop":"60","Tablet":""},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"0","right":"0","left":"0"}},"Tablet":[],"Mobile":[]},"prefix":"","number":"20","suffix":"","title":"Year Investment","showSupper":true,"superColor":{"r":233,"g":143,"b":80,"a":1},"superTypography":{"size":{"Desktop":{"point":"32","unit":"px"}},"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"lineHeight":{"Desktop":{"point":"0","unit":"px"}}},"numberColor":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"titleColor":{"Desktop":{"r":120,"g":120,"b":120,"a":1}},"numberTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"30","unit":"px"}},"spacing":{"Desktop":""},"lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"titleTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"0","unit":"px"}}},"numberBottomSpace":{"Mobile":"10"},"contentPadding":{"Desktop":[],"Mobile":[]},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<div class="guten-element guten-QSrQgk animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-stats-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="20" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Year Investment</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":null},"elementId":"guten-9Ph8mZ","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"15","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"bottom":"30","right":"0","left":"0","top":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-9Ph8mZ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="9Ph8mZ"><script>var top9Ph8mZ = {"Desktop":{"point":"0","unit":"px"}};var bottom9Ph8mZ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-RPFMWp","icon":"gtn gtn-apartment-light","iconColor":{"Desktop":{"r":233,"g":143,"b":80,"a":1}},"iconBorder":{"radius":{"Desktop":[],"Mobile":[]}},"iconSize":{"Desktop":"60"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"0","right":"0","left":"0"}},"Mobile":[]},"prefix":"","number":"150","suffix":"","title":"Year Investment","showSupper":true,"superColor":{"r":233,"g":143,"b":80,"a":1},"superTypography":{"size":{"Desktop":{"point":"32","unit":"px"}},"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"lineHeight":{"Desktop":{"point":"0","unit":"px"}}},"numberColor":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"titleColor":{"Desktop":{"r":120,"g":120,"b":120,"a":1}},"numberTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"30","unit":"px"}},"spacing":{"Desktop":""},"lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"titleTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"0","unit":"px"}}},"numberBottomSpace":{"Mobile":"10"},"contentPadding":{"Desktop":[],"Mobile":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"700"}} -->
			<div class="guten-element guten-RPFMWp animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-apartment-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="150" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Year Investment</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":null},"elementId":"guten-HAAFQe","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"15"}},"Mobile":{"unit":"px","dimension":{"bottom":"30","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-HAAFQe"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HAAFQe"><script>var topHAAFQe = {"Desktop":{"point":"0","unit":"px"}};var bottomHAAFQe = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-XyzRWs","icon":"gtn gtn-Consultancy-light","iconColor":{"Desktop":{"r":233,"g":143,"b":80,"a":1}},"iconBorder":{"radius":{"Desktop":[],"Mobile":[]}},"iconSize":{"Desktop":"60"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"0","right":"0","left":"0"}},"Mobile":[]},"prefix":"","number":"50","suffix":"","title":"Year Investment","showSupper":true,"superColor":{"r":233,"g":143,"b":80,"a":1},"superTypography":{"size":{"Desktop":{"point":"32","unit":"px"}},"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"lineHeight":{"Desktop":{"point":"0","unit":"px"}}},"numberColor":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"titleColor":{"Desktop":{"r":120,"g":120,"b":120,"a":1}},"numberTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"30","unit":"px"}},"spacing":{"Desktop":""},"lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"titleTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"0","unit":"px"}}},"numberBottomSpace":{"Mobile":"10"},"titleBottomSpace":{"Mobile":""},"contentPadding":{"Desktop":[],"Mobile":[]},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1000"}} -->
			<div class="guten-element guten-XyzRWs animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-Consultancy-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="50" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Year Investment</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":25,"Mobile":null},"elementId":"guten-5kZqtP","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"30","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-5kZqtP"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="5kZqtP"><script>var top5kZqtP = {"Desktop":{"point":"0","unit":"px"}};var bottom5kZqtP = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/fun-fact {"elementId":"guten-TiAtrs","icon":"gtn gtn-man-light","iconColor":{"Desktop":{"r":233,"g":143,"b":80,"a":1}},"iconBorder":{"radius":{"Desktop":[],"Mobile":[]}},"iconSize":{"Desktop":"60"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"14","bottom":"14","left":"14"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"0","right":"0","left":"0"}},"Mobile":[]},"prefix":"","number":"120","suffix":"","title":"Year Investment","showSupper":true,"superColor":{"r":233,"g":143,"b":80,"a":1},"superTypography":{"size":{"Desktop":{"point":"32","unit":"px"}},"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"lineHeight":{"Desktop":{"point":"0","unit":"px"}}},"numberColor":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"titleColor":{"Desktop":{"r":120,"g":120,"b":120,"a":1}},"numberTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"30","unit":"px"}},"spacing":{"Desktop":""},"lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"titleTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"point":"0","unit":"px"}}},"numberBottomSpace":{"Mobile":"10"},"contentPadding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":""}}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1300"}} -->
			<div class="guten-element guten-TiAtrs animated guten-element-hide desktop-fadeInUp guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="icon"><i class="gtn gtn-man-light"></i></div><div class="content"><div class="number-wrapper"><span class="prefix"> </span><span class="number loaded" data-number="120" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Year Investment</span></div></div></div>
			<!-- /wp:gutenverse/fun-fact --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
