<?php
/**
 * Gutenverse About Us content.
 */
return array(
	'title'      => __( 'Gutenverse About Us', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"elementId":"guten-HgFuDy","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"80","top":"100","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"40","right":"10","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"60","bottom":"20","right":"10","left":"10"}}}} -->
			<div class="section-wrapper" data-id="HgFuDy"><script>var topHgFuDy = {"Desktop":{"point":"0","unit":"px"}};var bottomHgFuDy = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-HgFuDy layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-g1zOos","margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","right":"80","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-g1zOos"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="g1zOos"><script>var topg1zOos = {"Desktop":{"point":"0","unit":"px"}};var bottomg1zOos = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-tuCbBe","type":5,"color":{"r":233,"g":143,"b":80,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
			<h5 class="wp-block-gutenverse-heading guten-element guten-tuCbBe animated guten-element-hide desktop-fadeInLeft">About Us</h5>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-sfa3e7","color":{"r":58,"g":58,"b":74,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"42","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"29"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-sfa3e7 animated guten-element-hide desktop-fadeInLeft">The Exclusive and Premium Property</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-e0uv61","textColor":{"r":120,"g":120,"b":120,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"25"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
			<div class="guten-element gutenverse-text-editor guten-e0uv61 animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque ullamcorper. Nullam commodo sem vitae nisl mollis vestibulum.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/button {"elementId":"guten-5QIzHE","content":"Contact Us","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"24","left":"24"}},"Tablet":[],"Mobile":[]},"buttonBackground":{"type":"default","color":{"r":233,"g":143,"b":80,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":233,"g":143,"b":80,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"color":{"r":233,"g":143,"b":80,"a":1},"type":"solid","width":"1"}},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"transform":"uppercase","weight":"400","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.1"}},"hoverTextColor":{"r":233,"g":143,"b":80,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-5QIzHE"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>Contact Us</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-pgCJoL","background":{"type":"default","image":{"Desktop":{"id":60,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/architecture-building-facade-property-apartment-modern-161021-pxhere.com.webp"}},"position":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"repeat":{"Desktop":"no-repeat"},"xposition":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"0","unit":"px"}},"yposition":{"Desktop":{"point":"-90","unit":"px"},"Tablet":{"point":"-5","unit":"px"}},"size":{"Desktop":"custom","Tablet":"cover"},"width":{"Desktop":{"point":"520","unit":"px"}}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":62,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/overlay-3.webp"}},"position":{"Desktop":"center center","Mobile":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"custom","Tablet":"cover","Mobile":"cover"},"width":{"Desktop":{"point":"530","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"xposition":{"Mobile":{"point":"-40","unit":"px"}},"yposition":{"Mobile":{"point":"0","unit":"px"}}},"opacity":"1","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"500"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-pgCJoL animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="pgCJoL"><script>var toppgCJoL = {"Desktop":{"point":"0","unit":"px"}};var bottompgCJoL = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-VdMtOJ","space":{"Desktop":{"point":"550","unit":"px"},"Tablet":{"point":"470","unit":"px"},"Mobile":{"point":"440","unit":"px"}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="guten-element guten-spacer guten-VdMtOJ"></div>
			<!-- /wp:gutenverse/spacer --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
