<?php
/**
 * Gutenverse About Team content.
 */
return array(
	'title'      => __( 'Gutenverse About Team', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-jE5fRc","margin":{"Desktop":{},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"30","bottom":"30","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20","bottom":"0","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"0","right":"20","left":"20"}}}} -->
			<div class="section-wrapper" data-id="jE5fRc"><script>var topjE5fRc = {"Desktop":{"point":"0","unit":"px"}};var bottomjE5fRc = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-jE5fRc layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-LHoN8d"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-LHoN8d"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="LHoN8d"><script>var topLHoN8d = {"Desktop":{"point":"0","unit":"px"}};var bottomLHoN8d = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-HhVHZV"} -->
			<div class="section-wrapper" data-id="HhVHZV"><script>var topHhVHZV = {"Desktop":{"point":"0","unit":"px"}};var bottomHhVHZV = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-HhVHZV layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-be5Fhi"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-be5Fhi"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="be5Fhi"><script>var topbe5Fhi = {"Desktop":{"point":"0","unit":"px"}};var bottombe5Fhi = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-qEaVEV","type":5,"textAlign":{"Desktop":"left"},"color":{"r":233,"g":143,"b":80,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
			<h5 class="wp-block-gutenverse-heading guten-element guten-qEaVEV animated guten-element-hide desktop-fadeInLeft">Our Team</h5>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-OOeia0","textAlign":{"Desktop":"left"},"color":{"r":58,"g":58,"b":74,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"42","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"0.7"},"Mobile":{"unit":"em","point":"1"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-OOeia0 animated guten-element-hide desktop-fadeInLeft">Meet Our Team</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-6ELjSL","alignment":{"Desktop":"left"},"textColor":{"r":120,"g":120,"b":120,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30","top":"10","right":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"","left":"","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<div class="guten-element gutenverse-text-editor guten-6ELjSL animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque ullamcorper.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-p600fn","verticalAlign":{"Desktop":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-p600fn"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="p600fn"><script>var topp600fn = {"Desktop":{"point":"0","unit":"px"}};var bottomp600fn = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-vVUtdp","content":"View All","alignButton":{"Desktop":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"24","left":"24"}},"Mobile":[],"Tablet":[]},"buttonBackground":{"type":"default","color":{"r":233,"g":143,"b":80,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":233,"g":143,"b":80,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"color":{"r":233,"g":143,"b":80,"a":1},"type":"solid","width":"1"}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"transform":"uppercase","weight":"400","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.1"}},"hoverTextColor":{"r":233,"g":143,"b":80,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-vVUtdp"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>View All</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-3FX1Y1","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"80","top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"60","left":""}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"40","bottom":"100"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="section-wrapper" data-id="3FX1Y1"><script>var top3FX1Y1 = {"Desktop":{"point":"0","unit":"px"}};var bottom3FX1Y1 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-3FX1Y1 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100,"Mobile":null},"elementId":"guten-lSYSih","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-lSYSih"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="lSYSih"><script>var toplSYSih = {"Desktop":{"point":"0","unit":"px"}};var bottomlSYSih = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-sncPyv","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":291,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/laptop-notebook-work-hand-suit-people-1278242-pxhere.com.webp"},"name":"","job":"","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"descColor":{"r":255,"g":255,"b":255,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":""}},"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"border":{"radius":{"Desktop":[]}},"profileBorder":{"radius":{"Desktop":[],"Tablet":[]}},"imageBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"},"imgWidth":{"Tablet":{"unit":"%","point":"100"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"380","unit":"px"},"Tablet":{"unit":"%","point":"100"}},"imgSpacing":{"Tablet":""},"hoverPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":""}}},"nameSpace":{"Desktop":"-40"},"jobSpace":{"Desktop":"0"},"descSpace":{"Desktop":"0"},"hoverContentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]}}} -->
			<div class="wp-block-gutenverse-team guten-element guten-team guten-sncPyv animated guten-element-hide desktop-fadeInUp"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( RESTANCE_URI ) . 'assets/img/laptop-notebook-work-hand-suit-people-1278242-pxhere.com.webp" alt=""/><div class="profile-body bottom"><h3 class="profile-title "></h3><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-LvGJKL","iconSize":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"30","unit":"px"},"Mobile":{"point":"17","unit":"px"}},"gap":{"Desktop":"20","Tablet":"25","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":233,"g":143,"b":80,"a":1},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"hoverIconColor":{"r":233,"g":143,"b":80,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="guten-element guten-social-icons guten-LvGJKL circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-lxf3Sv"} -->
			<div class="guten-element guten-social-icon guten-lxf3Sv facebook"><a id="guten-lxf3Sv" href="#"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->

			<!-- wp:gutenverse/social-icon {"elementId":"guten-jSL3O7"} -->
			<div class="guten-element guten-social-icon guten-jSL3O7 twitter"><a id="guten-jSL3O7" href="#"><i class="fab fa-twitter"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->

			<!-- wp:gutenverse/social-icon {"elementId":"guten-hQNLcK"} -->
			<div class="guten-element guten-social-icon guten-hQNLcK instagram"><a id="guten-hQNLcK" href="#"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon --></div>
			<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
			<!-- /wp:gutenverse/team -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-CkoJGC","margin":{"Desktop":{"unit":"px","dimension":{"top":"-40"}},"Tablet":{"unit":"px","dimension":{"top":"-60"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Tablet":[]},"zIndex":{"Desktop":"10"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"700"}} -->
			<div class="section-wrapper" data-id="CkoJGC"><script>var topCkoJGC = {"Desktop":{"point":"0","unit":"px"}};var bottomCkoJGC = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-CkoJGC animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-sauU7v","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{}}},"boxShadow":{"horizontal":"0","vertical":"5","blur":"20","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-sauU7v"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="sauU7v"><script>var topsauU7v = {"Desktop":{"point":"0","unit":"px"}};var bottomsauU7v = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-ZruOWK","alignment":{"Desktop":"center"},"textColor":{"r":58,"g":58,"b":74,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="guten-element gutenverse-text-editor guten-ZruOWK"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Grace Hall</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-janaQB","alignment":{"Desktop":"center"},"textColor":{"r":120,"g":120,"b":120,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-10"}}},"padding":{"Desktop":[]}} -->
			<div class="guten-element gutenverse-text-editor guten-janaQB"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Agent Supervisor</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100,"Mobile":null},"elementId":"guten-7xJUy6","margin":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-7xJUy6"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="7xJUy6"><script>var top7xJUy6 = {"Desktop":{"point":"0","unit":"px"}};var bottom7xJUy6 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-YSL0iy","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":311,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/man-person-suit-people-hair-white-1166609-pxhere.com.webp"},"name":"","job":"","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"descColor":{"r":255,"g":255,"b":255,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"border":{"radius":{"Desktop":[]}},"profileBorder":{"radius":{"Desktop":[]}},"imageBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeIn"},"duration":"normal","delay":"700"},"imgWidth":{"Tablet":{"unit":"%","point":"100"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"380","unit":"px"},"Tablet":{"unit":"%","point":"100"}},"hoverPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"nameSpace":{"Desktop":"-40"},"jobSpace":{"Desktop":"0"},"descSpace":{"Desktop":"0"},"hoverContentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}}} -->
			<div class="wp-block-gutenverse-team guten-element guten-team guten-YSL0iy animated guten-element-hide desktop-fadeIn"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( RESTANCE_URI ) . 'assets/img/man-person-suit-people-hair-white-1166609-pxhere.com.webp" alt=""/><div class="profile-body bottom"><h3 class="profile-title "></h3><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-LY3t5a","iconSize":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"30","unit":"px"},"Mobile":{"point":"17","unit":"px"}},"gap":{"Desktop":"20","Tablet":"25","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":233,"g":143,"b":80,"a":1},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"hoverIconColor":{"r":233,"g":143,"b":80,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="guten-element guten-social-icons guten-LY3t5a circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-SwwBmu"} -->
			<div class="guten-element guten-social-icon guten-SwwBmu facebook"><a id="guten-SwwBmu" href="#"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->

			<!-- wp:gutenverse/social-icon {"elementId":"guten-7jXYLX"} -->
			<div class="guten-element guten-social-icon guten-7jXYLX twitter"><a id="guten-7jXYLX" href="#"><i class="fab fa-twitter"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->

			<!-- wp:gutenverse/social-icon {"elementId":"guten-dJFseO"} -->
			<div class="guten-element guten-social-icon guten-dJFseO instagram"><a id="guten-dJFseO" href="#"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon --></div>
			<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
			<!-- /wp:gutenverse/team -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-kW5laJ","margin":{"Desktop":{"unit":"px","dimension":{"top":"-40"}},"Tablet":{"unit":"px","dimension":{"top":"-60"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Tablet":[]},"zIndex":{"Desktop":"10"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1000"}} -->
			<div class="section-wrapper" data-id="kW5laJ"><script>var topkW5laJ = {"Desktop":{"point":"0","unit":"px"}};var bottomkW5laJ = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-kW5laJ animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-WH0n7t","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{}}},"boxShadow":{"horizontal":"0","vertical":"5","blur":"20","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-WH0n7t"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="WH0n7t"><script>var topWH0n7t = {"Desktop":{"point":"0","unit":"px"}};var bottomWH0n7t = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-sBzzVb","alignment":{"Desktop":"center"},"textColor":{"r":58,"g":58,"b":74,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="guten-element gutenverse-text-editor guten-sBzzVb"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Jonathan Doe</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-Hvnhom","alignment":{"Desktop":"center"},"textColor":{"r":120,"g":120,"b":120,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-10"}}},"padding":{"Desktop":[]}} -->
			<div class="guten-element gutenverse-text-editor guten-Hvnhom"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Sales Leader</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.333333333333336,"Tablet":100,"Mobile":null},"elementId":"guten-3vftEF","margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]},"animation":{"type":{"Desktop":"none"}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-3vftEF"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="3vftEF"><script>var top3vftEF = {"Desktop":{"point":"0","unit":"px"}};var bottom3vftEF = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/team {"elementId":"guten-ViyH3Z","profileType":"overlay","overlayType":"default","overlayPosition":"bottom","src":{"id":313,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/girl-young-business-businesswoman-office-stands-1456585-pxhere.com.webp"},"name":"","job":"","nameColor":{"r":255,"g":255,"b":255,"a":1},"nameTypography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"500"},"jobColor":{"r":255,"g":255,"b":255,"a":1},"descColor":{"r":255,"g":255,"b":255,"a":1},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"border":{"radius":{"Desktop":[]}},"profileBorder":{"radius":{"Desktop":[]}},"imageBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeIn"},"duration":"normal","delay":"1000"},"imgWidth":{"Tablet":{"unit":"%","point":"100"},"Mobile":{"unit":"%","point":"100"},"Desktop":{"point":"","unit":"px"}},"imgHeight":{"Desktop":{"point":"380","unit":"px"},"Tablet":{"unit":"%","point":"100"}},"hoverPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"nameSpace":{"Desktop":"-40"},"jobSpace":{"Desktop":"0"},"descSpace":{"Desktop":"0"},"hoverContentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]}}} -->
			<div class="wp-block-gutenverse-team guten-element guten-team guten-ViyH3Z animated guten-element-hide desktop-fadeIn"><div class="profile-box"><div class="profile-card card-overlay default"><img src="' . esc_url( RESTANCE_URI ) . 'assets/img/girl-young-business-businesswoman-office-stands-1456585-pxhere.com.webp" alt=""/><div class="profile-body bottom"><h3 class="profile-title "></h3><p class="profile-sub"></p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-7g1CLN","iconSize":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"30","unit":"px"},"Mobile":{"point":"17","unit":"px"}},"gap":{"Desktop":"20","Tablet":"25","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"r":255,"g":255,"b":255,"a":1},"bgColor":{"r":233,"g":143,"b":80,"a":1},"iconBorder":{"radius":{"Desktop":[]}},"itemPadding":{"Desktop":{"unit":"px","dimension":{"top":"12","right":"12","bottom":"12","left":"12"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"hoverIconColor":{"r":233,"g":143,"b":80,"a":1},"hoverBgColor":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="guten-element guten-social-icons guten-7g1CLN circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-3QZgY0"} -->
			<div class="guten-element guten-social-icon guten-3QZgY0 facebook"><a id="guten-3QZgY0" href="#"><i class="gtn gtn-facebook-light"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->

			<!-- wp:gutenverse/social-icon {"elementId":"guten-TzdjZu"} -->
			<div class="guten-element guten-social-icon guten-TzdjZu twitter"><a id="guten-TzdjZu" href="#"><i class="fab fa-twitter"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon -->

			<!-- wp:gutenverse/social-icon {"elementId":"guten-8O1Qiy"} -->
			<div class="guten-element guten-social-icon guten-8O1Qiy instagram"><a id="guten-8O1Qiy" href="#"><i class="gtn gtn-instagram-1-light"></i><span></span></a></div>
			<!-- /wp:gutenverse/social-icon --></div>
			<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
			<!-- /wp:gutenverse/team -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-vHfDM0","border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-40"}},"Tablet":{"unit":"px","dimension":{"top":"-60"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40"}},"Tablet":[]},"zIndex":{"Desktop":"10"},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1300"}} -->
			<div class="section-wrapper" data-id="vHfDM0"><script>var topvHfDM0 = {"Desktop":{"point":"0","unit":"px"}};var bottomvHfDM0 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-vHfDM0 animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-cKUx9F","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{}}},"boxShadow":{"horizontal":"0","vertical":"5","blur":"20","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"margin":{"Desktop":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-cKUx9F"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="cKUx9F"><script>var topcKUx9F = {"Desktop":{"point":"0","unit":"px"}};var bottomcKUx9F = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/text-editor {"elementId":"guten-5NiZGJ","alignment":{"Desktop":"center"},"textColor":{"r":58,"g":58,"b":74,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="guten-element gutenverse-text-editor guten-5NiZGJ"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Jenny Doe</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-geI7Yv","alignment":{"Desktop":"center"},"textColor":{"r":120,"g":120,"b":120,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-10"}}},"padding":{"Desktop":[]}} -->
			<div class="guten-element gutenverse-text-editor guten-geI7Yv"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Manager</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
