<?php
/**
 * Gutenverse Home About content.
 */
return array(
	'title'      => __( 'Gutenverse Home About', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-2x0T2m"} -->
			<div class="section-wrapper" data-id="2x0T2m"><script>var top2x0T2m = {"Desktop":{"point":"0","unit":"px"}};var bottom2x0T2m = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-2x0T2m layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-AG1Fw6"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-AG1Fw6"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="AG1Fw6"><script>var topAG1Fw6 = {"Desktop":{"point":"0","unit":"px"}};var bottomAG1Fw6 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-0BQ92l","border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-100"}},"Tablet":{"unit":"px","dimension":{"top":"-100","right":"","left":""}},"Mobile":[]},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[]},"hideTablet":false,"hideMobile":true} -->
			<div class="section-wrapper" data-id="0BQ92l"><script>var top0BQ92l = {"Desktop":{"point":"0","unit":"px"}};var bottom0BQ92l = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-0BQ92l hide-mobile layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":39.17},"elementId":"guten-SlbHs0","border":{"radius":{"Tablet":[],"Desktop":{}}},"boxShadow":{"horizontal":"0","vertical":"5","blur":"30","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-SlbHs0 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="SlbHs0"><script>var topSlbHs0 = {"Desktop":{"point":"0","unit":"px"}};var bottomSlbHs0 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-6a9rM9","border":{"radius":{"Desktop":{},"Tablet":[]}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="section-wrapper" data-id="6a9rM9"><script>var top6a9rM9 = {"Desktop":{"point":"0","unit":"px"}};var bottom6a9rM9 = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-6a9rM9 layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-iuqQrF","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{}}},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40","top":"50","bottom":"50"}},"Tablet":[]},"animation":{"type":{"Desktop":"none"}},"hideTablet":true} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-iuqQrF hide-tablet"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="iuqQrF"><script>var topiuqQrF = {"Desktop":{"point":"0","unit":"px"}};var bottomiuqQrF = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-Hi4SWu","imgSrc":{"media":{"imageId":49,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( RESTANCE_URI ) . 'assets/img/icon-apart-150x150.webp","orientation":"landscape"},"medium":{"height":249,"width":300,"url":"' . esc_url( RESTANCE_URI ) . 'assets/img/icon-apart-300x249.webp","orientation":"landscape"},"full":{"url":"' . esc_url( RESTANCE_URI ) . 'assets/img/icon-apart.webp","height":315,"width":380,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"70","unit":"px"}},"imgBorder":{"radius":{"Desktop":{}}},"align":{"Desktop":"left"}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-Hi4SWu"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( RESTANCE_URI ) . 'assets/img/icon-apart.webp" height="315" width="380"/></a></div>
			<!-- /wp:gutenverse/image -->

			<!-- wp:gutenverse/heading {"elementId":"guten-c1ifg8","color":{"r":58,"g":58,"b":74,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"10","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":""}}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-c1ifg8">New Property will Be Ready</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-dKGNVO","textColor":{"r":120,"g":120,"b":120,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20","top":"5","bottom":"0","left":"0"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-dKGNVO"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-jN15v4","background":{"type":"default","color":{"r":244,"g":244,"b":244,"a":1}},"verticalAlign":{"Desktop":"center"},"border":{"radius":{"Tablet":[],"Desktop":{}}},"margin":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40","top":"50","bottom":"50"}},"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-jN15v4"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="jN15v4"><script>var topjN15v4 = {"Desktop":{"point":"0","unit":"px"}};var bottomjN15v4 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-lEGEws","color":{"r":58,"g":58,"b":74,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"26","unit":"px"}}},"border":{"radius":{"Tablet":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":""}}}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-lEGEws">Be The First</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-zVosaO","textColor":{"r":120,"g":120,"b":120,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.5"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"20","left":""}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"20","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"40"}}}} -->
			<div class="guten-element gutenverse-text-editor guten-zVosaO"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/button {"elementId":"guten-jJ2BUs","content":"Contact Us","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"24","left":"24"}}},"buttonBackground":{"type":"default","color":{"r":233,"g":143,"b":80,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":233,"g":143,"b":80,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"color":{"r":233,"g":143,"b":80,"a":1},"type":"solid","width":"1"}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"transform":"uppercase","weight":"400","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.1"}},"hoverTextColor":{"r":233,"g":143,"b":80,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-jJ2BUs"><a class="guten-button guten-button-sm" href="#"><span>Contact Us</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50},"elementId":"guten-XDGCuz","margin":{"Tablet":[]},"padding":{"Tablet":[]},"hideTablet":true} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-XDGCuz hide-tablet"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="XDGCuz"><script>var topXDGCuz = {"Desktop":{"point":"0","unit":"px"}};var bottomXDGCuz = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/section {"isChild":true,"elementId":"guten-HgFuDy","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"40","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"right":"","left":"","top":"","bottom":"60"}}}} -->
			<div class="section-wrapper" data-id="HgFuDy"><script>var topHgFuDy = {"Desktop":{"point":"0","unit":"px"}};var bottomHgFuDy = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-HgFuDy layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":null},"elementId":"guten-g1zOos","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"10"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","right":"80","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"40","top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-g1zOos"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="g1zOos"><script>var topg1zOos = {"Desktop":{"point":"0","unit":"px"}};var bottomg1zOos = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-tuCbBe","color":{"r":233,"g":143,"b":80,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-tuCbBe animated guten-element-hide desktop-fadeInLeft">About Us</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-sfa3e7","color":{"r":58,"g":58,"b":74,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"42","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-sfa3e7 animated guten-element-hide desktop-fadeInLeft">The Exclusive and Premium Property</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-e0uv61","textColor":{"r":120,"g":120,"b":120,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"29"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
			<div class="guten-element gutenverse-text-editor guten-e0uv61 animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque ullamcorper. Nullam commodo sem vitae nisl mollis vestibulum.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/button {"elementId":"guten-5QIzHE","content":"Contact Us","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"24","left":"24"}}},"buttonBackground":{"type":"default","color":{"r":233,"g":143,"b":80,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":233,"g":143,"b":80,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"color":{"r":233,"g":143,"b":80,"a":1},"type":"solid","width":"1"}},"margin":{"Desktop":{}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"transform":"uppercase","weight":"400","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.1"}},"hoverTextColor":{"r":233,"g":143,"b":80,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-5QIzHE"><a class="guten-button animated guten-element-hide desktop-fadeInLeft guten-button-sm" href="#"><span>Contact Us</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":null},"elementId":"guten-pgCJoL","background":{"type":"default","image":{"Desktop":{"id":60,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/architecture-building-facade-property-apartment-modern-161021-pxhere.com.webp"}},"position":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"repeat":{"Desktop":"no-repeat","Tablet":"no-repeat","Mobile":"default"},"xposition":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"0","unit":"px"},"Tablet":{"point":"1","unit":"px"}},"yposition":{"Desktop":{"point":"-90","unit":"px"},"Mobile":{"point":"-5","unit":"px"},"Tablet":{"point":"-5","unit":"px"}},"size":{"Desktop":"custom","Tablet":"cover","Mobile":"cover"},"width":{"Desktop":{"point":"520","unit":"px"},"Mobile":{"point":"300","unit":"px"}}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":62,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/overlay-3.webp"}},"position":{"Desktop":"center center","Mobile":"custom"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"custom","Mobile":"cover","Tablet":"cover"},"width":{"Desktop":{"point":"530","unit":"px"},"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"600","unit":"px"}},"xposition":{"Mobile":{"point":"-40","unit":"px"}},"yposition":{"Mobile":{"point":"","unit":"px"}}},"opacity":"1","margin":{"Desktop":{"unit":"px","dimension":{"top":"-60","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"-120","right":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":""}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"500"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-pgCJoL animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="pgCJoL"><script>var toppgCJoL = {"Desktop":{"point":"0","unit":"px"}};var bottompgCJoL = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/spacer {"elementId":"guten-VdMtOJ","space":{"Desktop":{"point":"550","unit":"px"},"Tablet":{"point":"500","unit":"px"},"Mobile":{"point":"440","unit":"px"}}} -->
			<div class="guten-element guten-spacer guten-VdMtOJ"></div>
			<!-- /wp:gutenverse/spacer --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
