<?php
/**
 * Gutenverse Home Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-P6sVWZ","background":{"type":"default","image":{"Desktop":{"id":60,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/floor-home-decoration-cottage-color-property-943456-pxhere.com.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"cover"},"repeat":{"Desktop":"no-repeat"},"yposition":{"Desktop":{"point":"","unit":"px"}},"xposition":{"Desktop":{"point":"","unit":"px"}},"color":{"r":0,"g":0,"b":0,"a":1}},"backgroundOverlay":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0.65},"gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":3,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","id":7,"offset":"0.107","active":false},{"color":"rgba(255, 255, 255, 0)","active":true,"id":6,"offset":"0.190"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":5,"offset":"0.293"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":4,"offset":"0.937"}],"gradientType":"linear","gradientAngle":270,"image":{"Desktop":{"id":1506,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/shape-divider-3.webp"}},"position":{"Desktop":"bottom right","Tablet":"bottom right","Mobile":"bottom right"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"xposition":{"Desktop":{"point":"107","unit":"px"},"Tablet":{"point":"1","unit":"px"},"Mobile":{"point":"200","unit":"px"}},"width":{"Desktop":{"point":"1250","unit":"px"},"Tablet":{"point":"900","unit":"px"},"Mobile":{"point":"750","unit":"px"}},"yposition":{"Tablet":{"point":"174","unit":"px"},"Mobile":{"point":"260","unit":"px"}}},"opacity":"1","border":{"radius":{"Desktop":[]}},"topDivider":{"width":{"Tablet":"","Mobile":""},"height":{"Tablet":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"0","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"300","bottom":"200","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"250","bottom":"200","right":"20","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"250","bottom":"200"}}},"zIndex":{"Desktop":""}} -->
			<div class="section-wrapper" data-id="P6sVWZ"><script>var topP6sVWZ = {"Desktop":{"point":"0","unit":"px"}};var bottomP6sVWZ = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-P6sVWZ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":55,"Tablet":68.22},"elementId":"guten-gMbq1V","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-gMbq1V"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="gMbq1V"><script>var topgMbq1V = {"Desktop":{"point":"0","unit":"px"}};var bottomgMbq1V = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-YGeLNv","color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"90","unit":"px"},"Tablet":{"point":"72","unit":"px"},"Mobile":{"point":"54","unit":"px"}},"spacing":{"Desktop":""},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"40"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"right":"20"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-YGeLNv animated guten-element-hide desktop-fadeInLeft">The Real Dream Living</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-Hi9Wz1","textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.8"}}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"80","top":"","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"}} -->
			<div class="guten-element gutenverse-text-editor guten-Hi9Wz1 animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque ullamcorper.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":45,"Tablet":null},"elementId":"guten-HbZ57J","margin":{"Tablet":[]},"padding":{"Tablet":[]},"hideTablet":true} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-HbZ57J hide-tablet"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HbZ57J"><script>var topHbZ57J = {"Desktop":{"point":"0","unit":"px"}};var bottomHbZ57J = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
