<?php
/**
 * Gutenverse Single Post Hero content.
 */
return array(
	'title'      => __( 'Gutenverse Single Post Hero', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-9rsSZi","background":{"type":"default","image":{"Desktop":{"id":1353,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/architecture-structure-window-building-skyscraper-urban-1001301-pxhere.com.webp"}},"position":{"Desktop":"center center","Tablet":"center center","Mobile":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"xposition":{"Desktop":{"point":"0","unit":"px"}},"yposition":{"Desktop":{"point":"-200","unit":"px"}}},"backgroundOverlay":{"type":"default","color":{"r":3,"g":3,"b":3,"a":0.8}},"opacity":"1","margin":{"Desktop":{"unit":"px","dimension":{"top":"-148","right":"","bottom":"","left":""}},"Tablet":{},"Mobile":{}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"230","bottom":"160","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"230","bottom":"160","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"230","bottom":"160","right":"0","left":"0"}}}} -->
			<div class="section-wrapper" data-id="9rsSZi"><script>var top9rsSZi = {"Desktop":{"point":"0","unit":"px"}};var bottom9rsSZi = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-9rsSZi layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-a93VDD","verticalAlign":{"Desktop":"default","Tablet":"default"},"horizontalAlign":{"Desktop":"center","Tablet":"default"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-a93VDD"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="a93VDD"><script>var topa93VDD = {"Desktop":{"point":"0","unit":"px"}};var bottoma93VDD = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/post-title {"elementId":"guten-9H20W3","alignment":{"Desktop":"center","Tablet":"center"},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"52","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"weight":"600"},"color":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"0","top":"8","bottom":"36"}},"Tablet":{"unit":"%","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}},"padding":{"Desktop":{},"Tablet":{"unit":"px","dimension":{"right":"80","left":"80","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} -->
			<div class="guten-element guten-post-title guten-9H20W3 animated guten-element-hide desktop-fadeInUp"></div>
			<!-- /wp:gutenverse/post-title -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-phUR4P","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<div class="section-wrapper" data-id="phUR4P"><script>var topphUR4P = {"Desktop":{"point":"0","unit":"px"}};var bottomphUR4P = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-phUR4P animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-qSiPOj","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-qSiPOj"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="qSiPOj"><script>var topqSiPOj = {"Desktop":{"point":"0","unit":"px"}};var bottomqSiPOj = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon {"elementId":"guten-g8pX5K","icon":"fas fa-calendar-alt","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"16","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"r":255,"g":179,"b":129,"a":1},"background":{"type":"default","color":""},"positioningType":{"Desktop":"inline"}} -->
			<div class="wp-block-gutenverse-icon guten-element guten-g8pX5K guten-icon"><span class="guten-icon-wrapper rounded stacked"><i class="fas fa-calendar-alt"></i></span></div>
			<!-- /wp:gutenverse/icon -->

			<!-- wp:gutenverse/post-date {"elementId":"guten-6M0Zvs","typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"500"},"color":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":""}}},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-post-date guten-6M0Zvs"></div>
			<!-- /wp:gutenverse/post-date -->

			<!-- wp:gutenverse/icon {"elementId":"guten-biINo7","icon":"fas fa-user-circle","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"16","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"r":255,"g":179,"b":129,"a":1},"background":{"type":"default","color":""},"margin":{"Desktop":{"unit":"px","dimension":{"left":"40"}}},"padding":{"Desktop":{}},"positioningType":{"Desktop":"inline"}} -->
			<div class="wp-block-gutenverse-icon guten-element guten-biINo7 guten-icon"><span class="guten-icon-wrapper rounded stacked"><i class="fas fa-user-circle"></i></span></div>
			<!-- /wp:gutenverse/icon -->

			<!-- wp:gutenverse/post-author {"elementId":"guten-LzHUTf","typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"500"},"color":{"r":255,"g":255,"b":255,"a":1},"margin":{"Desktop":{"unit":"px","dimension":{"left":"10"}}},"padding":{"Desktop":{}},"positioningType":{"Desktop":"inline"}} -->
			<div class="guten-element guten-post-author guten-LzHUTf"></div>
			<!-- /wp:gutenverse/post-author --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
