<?php
/**
 * Gutenverse Home Logo Client content.
 */
return array(
	'title'      => __( 'Gutenverse Home Logo Client', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-xAykyT"} -->
			<div class="section-wrapper" data-id="xAykyT"><script>var topxAykyT = {"Desktop":{"point":"0","unit":"px"}};var bottomxAykyT = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-xAykyT layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-7rIajR","horizontalAlign":{"Desktop":"default"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-7rIajR"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="7rIajR"><script>var top7rIajR = {"Desktop":{"point":"0","unit":"px"}};var bottom7rIajR = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-EAuA4i"} -->
			<div class="section-wrapper" data-id="EAuA4i"><script>var topEAuA4i = {"Desktop":{"point":"0","unit":"px"}};var bottomEAuA4i = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-EAuA4i layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-7HYZS7"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-7HYZS7"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="7HYZS7"><script>var top7HYZS7 = {"Desktop":{"point":"0","unit":"px"}};var bottom7HYZS7 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-SjQqTZ","textAlign":{"Desktop":"center"},"color":{"r":233,"g":143,"b":80,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-SjQqTZ animated guten-element-hide desktop-fadeInUp">Official Partner</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-b5qzob","textAlign":{"Desktop":"center"},"color":{"r":58,"g":58,"b":74,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"42","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"0.7"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-b5qzob animated guten-element-hide desktop-fadeInUp">Our Partner</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-vHtKgd","alignment":{"Desktop":"center"},"textColor":{"r":120,"g":120,"b":120,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"28","left":"28","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"30","bottom":"0","left":"40"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
			<div class="guten-element gutenverse-text-editor guten-vHtKgd animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque ullamcorper.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/section {"isChild":true,"height":{"Desktop":{"point":"","unit":"px"}},"gap":"no","elementId":"guten-QqvXAT","heightControl":"min","margin":{"Mobile":[],"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"padding":{"Mobile":[],"Desktop":{"unit":"px","dimension":{"top":"30","bottom":"20"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"animation":{"type":{"Desktop":"fadeIn"},"duration":"normal","delay":"400"}} -->
			<div class="section-wrapper" data-id="QqvXAT"><script>var topQqvXAT = {"Desktop":{"point":"0","unit":"px"}};var bottomQqvXAT = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-QqvXAT animated guten-element-hide desktop-fadeIn layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-889Ltw","verticalAlign":{"Desktop":"center"},"horizontalAlign":{"Desktop":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"30"}},"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Mobile":[],"Desktop":[]}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-889Ltw"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="889Ltw"><script>var top889Ltw = {"Desktop":{"point":"0","unit":"px"}};var bottom889Ltw = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/logo-slider {"elementId":"guten-r0fre3","logos":[{"title":"One","_key":"BmkMJW","src":{"id":86,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-5.webp"},"hoverSrc":[]},{"title":"Two","_key":"3GBWkE","src":{"id":87,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-4.webp"},"hoverSrc":[]},{"title":"Three","_key":"YqsvFO","src":{"id":88,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-1.webp"},"hoverSrc":[]},{"title":"four","src":{"id":89,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-2.webp"},"hoverSrc":[],"_key":"1rrw1e"},{"title":"Five","src":{"id":90,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-3.webp"},"hoverSrc":[],"_key":"OYugX6"}],"imageHeight":{"Desktop":""},"imageFit":{"Desktop":"cover"},"imagePadding":{"Desktop":{"unit":"px","dimension":{"top":"52","right":"52","bottom":"52","left":"52"}},"Tablet":{"unit":"%","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"70","bottom":"0","left":"70"}}},"imageMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"imageHoverPadding":{"Desktop":{"unit":"px","dimension":{"top":"52","right":"52","bottom":"52","left":"52"}},"Tablet":{"unit":"%","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"70","bottom":"0","left":"70"}}},"imageHoverMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"imageBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"imageBorderHover":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]}},"spacing":{"Desktop":"1","Tablet":"0","Mobile":""},"itemShowed":{"Desktop":"4","Tablet":"3","Mobile":"1"},"loop":true,"dotsRadius":{"Desktop":[]},"arrowFontSize":{"Desktop":""},"arrowPadding":{"Desktop":[],"Mobile":[]},"arrowMargin":{"Desktop":[],"Mobile":[]},"arrowHoverPadding":{"Desktop":[]},"arrowHoverMargin":{"Desktop":[]},"arrowBorder":{"radius":{"Desktop":[],"Mobile":[]}},"arrowBorderHover":{"radius":{"Desktop":[]}},"border":{"radius":{"Desktop":[]}},"opacity":"0.4","hoverOpacity":"1","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"40"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]}} -->
			<div class="guten-element guten-client-logo grid-desktop-3 guten-r0fre3 arrow-bottom-edge"><div class="client-list"><div id="guten-r0fre3" class="swiper-container" data-loop="true" data-autoplay="false" data-timeout="2400" data-nav="false" data-arrow="false" data-breakpoints="{&quot;0&quot;:{&quot;spaceBetween&quot;:10,&quot;slidesPerView&quot;:1},&quot;768&quot;:{&quot;spaceBetween&quot;:0,&quot;slidesPerView&quot;:3},&quot;1024&quot;:{&quot;spaceBetween&quot;:1,&quot;slidesPerView&quot;:4}}"><div class="swiper-wrapper"><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-5.webp" alt="One"/><img class="hover-image" src="' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-5.webp" alt="One"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-4.webp" alt="Two"/><img class="hover-image" src="' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-4.webp" alt="Two"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-1.webp" alt="Three"/><img class="hover-image" src="' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-1.webp" alt="Three"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-2.webp" alt="four"/><img class="hover-image" src="' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-2.webp" alt="four"/></div></div><div class="swiper-slide image-list"><div class="content-image"><img class="main-image" src="' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-3.webp" alt="Five"/><img class="hover-image" src="' . esc_url( RESTANCE_URI ) . 'assets/img/Logoipsum-3.webp" alt="Five"/></div></div></div></div></div></div>
			<!-- /wp:gutenverse/logo-slider --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
