<?php
/**
 * Gutenverse Contact Us content.
 */
return array(
	'title'      => __( 'Gutenverse Contact Us', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-ClCmkW","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"20","left":"20"}}}} -->
			<div class="section-wrapper" data-id="ClCmkW"><script>var topClCmkW = {"Desktop":{"point":"0","unit":"px"}};var bottomClCmkW = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-ClCmkW layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-nLuSof","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","left":"0","right":"80"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-nLuSof"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="nLuSof"><script>var topnLuSof = {"Desktop":{"point":"0","unit":"px"}};var bottomnLuSof = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-SjQqTZ","type":5,"textAlign":{"Desktop":"left"},"color":{"r":233,"g":143,"b":80,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"10","left":""}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
			<h5 class="wp-block-gutenverse-heading guten-element guten-SjQqTZ animated guten-element-hide desktop-fadeInLeft">Contact Us</h5>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-7gNhi7","textAlign":{"Mobile":"left"},"color":{"r":58,"g":58,"b":74,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"42","unit":"px"},"Tablet":{"point":"42","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"weight":"600","transform":"default","spacing":{"Desktop":"0.01"},"lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":{}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-7gNhi7 animated guten-element-hide desktop-fadeInLeft">Get in touch</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-2t2CRP","alignment":{"Mobile":"left"},"textColor":{"r":120,"g":120,"b":120,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"26","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"0","right":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{},"Tablet":{"unit":"%","dimension":{"top":"0","right":"15","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
			<div class="guten-element gutenverse-text-editor guten-2t2CRP animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-THWG1X","margin":{"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Desktop":[]},"padding":{"Mobile":[],"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
			<div class="section-wrapper" data-id="THWG1X"><script>var topTHWG1X = {"Desktop":{"point":"0","unit":"px"}};var bottomTHWG1X = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-THWG1X animated guten-element-hide desktop-fadeInLeft layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-Cl47t1","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Cl47t1"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Cl47t1"><script>var topCl47t1 = {"Desktop":{"point":"0","unit":"px"}};var bottomCl47t1 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-KE0oSg","title":"Ubud, Bali","titleTag":"h3","description":"Jl. Raya Mas Ubud No.88, Bali 80571","icon":"gtn gtn-cityscape-light","iconSize":{"Desktop":"65","Mobile":"55"},"iconPosition":"left","align":{"Desktop":"flex-start"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"}},"iconPadding":{"Desktop":[],"Mobile":[]},"iconMargin":{"Desktop":[],"Mobile":[]},"iconColor":{"r":233,"g":143,"b":80,"a":1},"iconBorder":{"radius":{"Desktop":[],"Mobile":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"0","left":"10"}},"Mobile":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleColor":{"r":58,"g":58,"b":74,"a":1},"titleTypography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}}},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"0","left":"10"}},"Mobile":[]},"descColor":{"r":120,"g":120,"b":120,"a":1},"descTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"weight":"300","size":{"Mobile":{"point":"14","unit":"px"}}},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"25","right":"","bottom":"30","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="guten-element guten-KE0oSg guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-cityscape-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Ubud, Bali</h3><p class="icon-box-description">Jl. Raya Mas Ubud No.88, Bali 80571</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/google-maps {"elementId":"guten-9NxnX6","location":"renon","zoom":"17","height":{"Desktop":"350"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"500"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{}}} -->
			<div class="guten-element gutenverse-maps guten-9NxnX6 animated guten-element-hide desktop-fadeInLeft"><iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?q=renon&amp;z=17&amp;t=m&amp;output=embed&amp;iwloc=near" title="renon"></iframe></div>
			<!-- /wp:gutenverse/google-maps --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-S5Bv0G","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"border":{"radius":{"Desktop":{}}},"boxShadow":{"horizontal":"0","vertical":"5","blur":"30","spread":"0","color":{"r":16,"g":16,"b":10,"a":0.1}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Tablet":{"unit":"px","dimension":{"top":"60","right":"60","bottom":"60","left":"60"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"20","left":"30"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"800"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-S5Bv0G animated guten-element-hide desktop-fadeInRight"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="S5Bv0G"><script>var topS5Bv0G = {"Desktop":{"point":"0","unit":"px"}};var bottomS5Bv0G = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-xLQcqQ","textAlign":{"Mobile":"center"},"color":{"r":58,"g":58,"b":74,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"weight":"600","transform":"default","spacing":{"Desktop":"0.01"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":[]}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-xLQcqQ">Your Details</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/form-builder {"elementId":"guten-eYTuM9","hideAfterSubmit":false,"border":{"radius":{"Desktop":[]}},"borderHover":{"radius":{"Desktop":[]}},"margin":{"Tablet":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<form style="display:none" class="guten-element guten-form-builder guten-eYTuM9" data-hide-after="false"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-qvvolu","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Desktop":[]}} -->
			<div class="section-wrapper" data-id="qvvolu"><script>var topqvvolu = {"Desktop":{"point":"0","unit":"px"}};var bottomqvvolu = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-qvvolu layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":null},"elementId":"guten-IEyoBX","margin":{"Desktop":{"unit":"px","dimension":{"right":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-IEyoBX"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="IEyoBX"><script>var topIEyoBX = {"Desktop":{"point":"0","unit":"px"}};var bottomIEyoBX = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-text {"elementId":"guten-oL8Hgj","inputLabel":"First Name","inputPlaceholder":"Your Name","showHelper":false,"labelColor":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"labelTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"600"},"labelPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":[]},"labelMargin":{"Desktop":[],"Tablet":[]},"helperColor":{"Tablet":[]},"helperPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"required":true,"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"12","bottom":"6","left":"30"}},"Tablet":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Tablet":[]},"placeholderColor":{"Desktop":{"r":120,"g":120,"b":120,"a":1},"Tablet":[]},"inputTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"36","unit":"px"}}},"inputColorNormal":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"inputBorderNormal":{"radius":{"Desktop":[],"Tablet":[]},"all":{"type":"solid","width":"1","color":{"r":233,"g":233,"b":233,"a":1}}},"inputColorHover":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"r":24,"g":24,"b":24,"a":1}}},"inputColorFocus":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":24,"g":24,"b":24,"a":1}}},"inputBgColorHover":{"Desktop":[]}} -->
			<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-oL8Hgj hide-helper"><div class="label-wrapper"><label class="input-label">First Name</label><span class="required-badge">*</span></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:true,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-text --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"elementId":"guten-HpSeEG","margin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-HpSeEG"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HpSeEG"><script>var topHpSeEG = {"Desktop":{"point":"0","unit":"px"}};var bottomHpSeEG = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/form-input-text {"elementId":"guten-rthzO7","inputLabel":"Email Address","inputPlaceholder":"Your Email","showHelper":false,"labelColor":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"labelTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"12","unit":"px"}}},"labelPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":[]},"labelMargin":{"Desktop":[],"Tablet":[]},"helperPadding":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"required":true,"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"12","bottom":"6","left":"30"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"placeholderColor":{"Desktop":{"r":120,"g":120,"b":120,"a":1}},"inputTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"36","unit":"px"}}},"inputColorNormal":{"Desktop":{"r":24,"g":24,"b":24,"a":1}},"inputBorderNormal":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"r":233,"g":233,"b":233,"a":1}}},"inputColorHover":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"r":58,"g":58,"b":74,"a":1}}},"inputColorFocus":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"r":24,"g":24,"b":24,"a":1}}},"inputBgColorHover":{"Desktop":[]}} -->
			<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-rthzO7 hide-helper"><div class="label-wrapper"><label class="input-label">Email Address</label><span class="required-badge">*</span></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:true,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-text --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/form-input-text {"elementId":"guten-jaCw7N","inputLabel":"Subject","inputPlaceholder":"Your Subject","showHelper":false,"labelColor":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"labelTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"600"},"labelPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":[]},"labelMargin":{"Desktop":[],"Tablet":[]},"helperPadding":{"Desktop":[]},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"required":true,"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"6","right":"12","bottom":"6","left":"30"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"placeholderColor":{"Desktop":{"r":120,"g":120,"b":120,"a":1}},"inputTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"36","unit":"px"}}},"inputColorNormal":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"inputBorderNormal":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"r":233,"g":233,"b":233,"a":1}}},"inputColorHover":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"r":58,"g":58,"b":74,"a":1}}},"inputColorFocus":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"r":24,"g":24,"b":24,"a":1}}},"inputBgColorHover":{"Desktop":[]}} -->
			<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-jaCw7N hide-helper"><div class="label-wrapper"><label class="input-label">Subject</label><span class="required-badge">*</span></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:true,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Subject" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-text -->

			<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-QQDDhH","showHelper":false,"labelColor":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"labelTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"12","unit":"px"}},"weight":"600"},"labelPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":[]},"labelMargin":{"Desktop":[],"Tablet":[]},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"inputHeight":{"Desktop":"176"},"inputLabel":"Comments / Questions","inputPlaceholder":"Your Message","required":true,"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"15","bottom":"6","right":"12","left":"30"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}}},"placeholderColor":{"Desktop":{"r":120,"g":120,"b":120,"a":1}},"inputTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"36","unit":"px"}}},"inputColorNormal":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"inputBorderNormal":{"radius":{"Desktop":[]},"all":{"color":{"r":233,"g":233,"b":233,"a":1},"type":"solid","width":"1"}},"inputColorHover":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"color":{"r":58,"g":58,"b":74,"a":1},"type":"solid","width":"1"}},"inputColorFocus":{"Desktop":{"r":58,"g":58,"b":74,"a":1}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"color":{"r":24,"g":24,"b":24,"a":1},"type":"solid","width":"1"}}} -->
			<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-QQDDhH hide-helper"><div class="label-wrapper"><label class="input-label">Comments / Questions</label><span class="required-badge">*</span></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:true,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Message" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
			<!-- /wp:gutenverse/form-input-textarea -->

			<!-- wp:gutenverse/button {"elementId":"guten-N94Rza","content":"Submit Message","buttonWidth":{"Desktop":""},"alignButton":{"Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"24","bottom":"18","left":"24"}},"Tablet":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"32","left":"32"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"r":233,"g":143,"b":80,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":233,"g":143,"b":80,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":233,"g":143,"b":80,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"40","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"400","transform":"uppercase","spacing":{"Desktop":"0.1","Mobile":"0.1"},"lineHeight":{"Desktop":{"point":"23","unit":"px"}}},"hoverTextColor":{"r":233,"g":143,"b":80,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-N94Rza"><a class="guten-button guten-button-sm" href="#"><span>Submit Message</span></a></div>
			<!-- /wp:gutenverse/button --></form>
			<!-- /wp:gutenverse/form-builder --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
