<?php
/**
 * Gutenverse About Featured content.
 */
return array(
	'title'      => __( 'Gutenverse About Featured', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-pA2xIm","margin":{"Desktop":{},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","right":"20","bottom":"60","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"","bottom":"0","left":""}}}} -->
			<div class="section-wrapper" data-id="pA2xIm"><script>var toppA2xIm = {"Desktop":{"point":"0","unit":"px"}};var bottompA2xIm = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-pA2xIm layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-uQMhiJ"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-uQMhiJ"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="uQMhiJ"><script>var topuQMhiJ = {"Desktop":{"point":"0","unit":"px"}};var bottomuQMhiJ = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-qn3P4x","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"40","right":"0","left":"0"}},"Tablet":[],"Mobile":[]}} -->
			<div class="section-wrapper" data-id="qn3P4x"><script>var topqn3P4x = {"Desktop":{"point":"0","unit":"px"}};var bottomqn3P4x = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-qn3P4x layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":45,"Tablet":60},"elementId":"guten-nRKeWA"} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-nRKeWA"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="nRKeWA"><script>var topnRKeWA = {"Desktop":{"point":"0","unit":"px"}};var bottomnRKeWA = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-I4OKDK","type":5,"textAlign":{"Desktop":"left"},"color":{"r":233,"g":143,"b":80,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
			<h5 class="wp-block-gutenverse-heading guten-element guten-I4OKDK animated guten-element-hide desktop-fadeInLeft">Commitment</h5>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-J0aNcl","textAlign":{"Desktop":"left"},"color":{"r":58,"g":58,"b":74,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"42","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"0.7"},"Mobile":{"unit":"em","point":"1"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-J0aNcl animated guten-element-hide desktop-fadeInLeft">Our Vision</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-2rwxvm","alignment":{"Desktop":"left"},"textColor":{"r":120,"g":120,"b":120,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"10","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"","left":"","top":"","bottom":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<div class="guten-element gutenverse-text-editor guten-2rwxvm animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque ullamcorper.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":55,"Tablet":40,"Mobile":null},"elementId":"guten-wYWPti","verticalAlign":{"Desktop":"center","Tablet":"center"},"margin":{"Mobile":[]},"padding":{"Mobile":[]}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-wYWPti"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="wYWPti"><script>var topwYWPti = {"Desktop":{"point":"0","unit":"px"}};var bottomwYWPti = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-UGZ9SV","content":"Learn More","alignButton":{"Desktop":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"24","left":"24"}},"Tablet":[],"Mobile":[]},"buttonBackground":{"type":"default","color":{"r":233,"g":143,"b":80,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":233,"g":143,"b":80,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"color":{"r":233,"g":143,"b":80,"a":1},"type":"solid","width":"1"}},"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"transform":"uppercase","weight":"400","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.1"}},"hoverTextColor":{"r":233,"g":143,"b":80,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-UGZ9SV"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>Learn More</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-duArME","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="section-wrapper" data-id="duArME"><script>var topduArME = {"Desktop":{"point":"0","unit":"px"}};var bottomduArME = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-duArME layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":62.013,"Tablet":100},"elementId":"guten-APnSiO","margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-APnSiO animated guten-element-hide desktop-fadeInLeft"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="APnSiO"><script>var topAPnSiO = {"Desktop":{"point":"0","unit":"px"}};var bottomAPnSiO = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/image {"elementId":"guten-Ua5kYb","imgSrc":{"media":{"imageId":1330,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( RESTANCE_URI ) . 'assets/img/room-living-room-interior-design-property-furniture-building-1632949-pxhere.com.webp","orientation":"landscape"},"medium":{"height":204,"width":300,"url":"' . esc_url( RESTANCE_URI ) . 'assets/img/room-living-room-interior-design-property-furniture-building-1632949-pxhere.com.webp","orientation":"landscape"},"large":{"height":698,"width":1024,"url":"' . esc_url( RESTANCE_URI ) . 'assets/img/room-living-room-interior-design-property-furniture-building-1632949-pxhere.com.webp","orientation":"landscape"},"full":{"url":"' . esc_url( RESTANCE_URI ) . 'assets/img/room-living-room-interior-design-property-furniture-building-1632949-pxhere.com.webp","height":1308,"width":1920,"orientation":"landscape"}}},"size":"full"},"captionOriginal":"","width":{"Desktop":{"point":"670","unit":"px"},"Tablet":{"point":"930","unit":"px"}},"height":{"Desktop":{"point":"640","unit":"px"},"Tablet":{"point":"641","unit":"px"},"Mobile":{"point":"257","unit":"px"}},"imgBorder":{"radius":{"Desktop":{},"Tablet":[],"Mobile":[]}},"imageFit":{"Desktop":"cover","Tablet":"cover","Mobile":"cover"},"animation":{"delay":"400"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"40","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-image guten-element guten-image guten-Ua5kYb"><a class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( RESTANCE_URI ) . 'assets/img/room-living-room-interior-design-property-furniture-building-1632949-pxhere.com.webp" height="1308" width="1920"/></a></div>
			<!-- /wp:gutenverse/image --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":37.98,"Tablet":100,"Mobile":null},"elementId":"guten-oY8ANE","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"40","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"50","right":"0","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-oY8ANE"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="oY8ANE"><script>var topoY8ANE = {"Desktop":{"point":"0","unit":"px"}};var bottomoY8ANE = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-ZoZK7w","title":"House for Everyone","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque.","icon":"gtn gtn-apartment1-light","iconSize":{"Desktop":"50"},"align":{"Desktop":"flex-start","Tablet":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"iconColor":{"r":233,"g":143,"b":80,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"r":58,"g":58,"b":74,"a":1},"titleTypography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"","unit":"px"},"Mobile":{"point":"","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"10","bottom":"20"}},"Tablet":{"unit":"%","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}}},"descColor":{"r":120,"g":120,"b":120,"a":1},"descTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Mobile":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
			<div class="guten-element guten-ZoZK7w animated guten-element-hide desktop-fadeInRight guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-apartment1-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">House for Everyone</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque.</p></div></div></div>
			<!-- /wp:gutenverse/icon-box -->

			<!-- wp:gutenverse/icon-box {"elementId":"guten-bqonOo","title":"Competitive Price","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque.","icon":"gtn gtn-coin-light","iconSize":{"Desktop":"50"},"align":{"Desktop":"flex-start","Tablet":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"containerBorder":{"radius":{"Desktop":[],"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"iconColor":{"r":233,"g":143,"b":80,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"r":58,"g":58,"b":74,"a":1},"titleTypography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Mobile":{"point":"","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"10","bottom":"20"}},"Tablet":{"unit":"%","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10"}}},"descColor":{"r":120,"g":120,"b":120,"a":1},"descTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"700"}} -->
			<div class="guten-element guten-bqonOo animated guten-element-hide desktop-fadeInRight guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-coin-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Competitive Price</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque.</p></div></div></div>
			<!-- /wp:gutenverse/icon-box -->

			<!-- wp:gutenverse/icon-box {"elementId":"guten-O01Ln9","title":"Long-Term Investment","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque.","icon":"gtn gtn-star-light","iconSize":{"Desktop":"50"},"align":{"Desktop":"flex-start","Tablet":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"containerBorder":{"radius":{"Desktop":[],"Tablet":{"unit":"px","dimension":[]}},"all":{"type":"none"}},"iconPadding":{"Desktop":{}},"iconMargin":{"Desktop":{}},"iconColor":{"r":233,"g":143,"b":80,"a":1},"iconBorder":{"radius":{"Desktop":{}}},"titlePadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Tablet":[],"Mobile":[]},"titleColor":{"r":58,"g":58,"b":74,"a":1},"titleTypography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"right":"10","bottom":"0"}},"Tablet":{"unit":"%","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10"}}},"descColor":{"r":120,"g":120,"b":120,"a":1},"descTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"1000"}} -->
			<div class="guten-element guten-O01Ln9 animated guten-element-hide desktop-fadeInRight guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-star-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Long-Term Investment</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque.</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
