<?php
/**
 * Gutenverse FAQ Benefits content.
 */
return array(
	'title'      => __( 'Gutenverse FAQ Benefits', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-phucwG","background":{"type":"default","image":{"Desktop":{"id":143,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/architecture-structure-white-texture-floor-wall.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"contain"},"repeat":{"Desktop":"repeat"}},"backgroundOverlay":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"opacity":"0.2","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"80","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"60","bottom":"40","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"","left":""}}}} -->
			<div class="section-wrapper" data-id="phucwG"><script>var topphucwG = {"Desktop":{"point":"0","unit":"px"}};var bottomphucwG = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-phucwG layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-vDd6Yf","horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10","left":"10"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-vDd6Yf"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vDd6Yf"><script>var topvDd6Yf = {"Desktop":{"point":"0","unit":"px"}};var bottomvDd6Yf = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-SbXRBr","type":5,"textAlign":{"Desktop":"left"},"color":{"r":233,"g":143,"b":80,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
			<h5 class="wp-block-gutenverse-heading guten-element guten-SbXRBr animated guten-element-hide desktop-fadeInLeft">Our Benefits</h5>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-7XSY9p","textAlign":{"Desktop":"left"},"color":{"r":58,"g":58,"b":74,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"42","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-7XSY9p animated guten-element-hide desktop-fadeInLeft">The Benefits</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-Si6RDk","alignment":{"Desktop":"left"},"textColor":{"r":120,"g":120,"b":120,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"55","left":"","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<div class="guten-element gutenverse-text-editor guten-Si6RDk animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque ullamcorper.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-sXfPmY"} -->
			<div class="section-wrapper" data-id="sXfPmY"><script>var topsXfPmY = {"Desktop":{"point":"0","unit":"px"}};var bottomsXfPmY = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-sXfPmY layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null},"elementId":"guten-fKhp33","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-fKhp33 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="fKhp33"><script>var topfKhp33 = {"Desktop":{"point":"0","unit":"px"}};var bottomfKhp33 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-KjAbux","title":"Good Traffic","titleTag":"h3","description":"Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit","icon":"gtn gtn-car-2-light","iconSize":{"Desktop":"70","Tablet":"45"},"align":{"Desktop":"flex-start","Mobile":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"80","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[],"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconColor":{"r":233,"g":143,"b":80,"a":1},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Tablet":[]},"titleMargin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"titleColor":{"r":58,"g":58,"b":74,"a":1},"titleTypography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":""}}},"descColor":{"r":120,"g":120,"b":120,"a":1},"descTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
			<div class="guten-element guten-KjAbux guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-car-2-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Good Traffic</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null,"Mobile":null},"elementId":"guten-lrIkYI","margin":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-lrIkYI animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="lrIkYI"><script>var toplrIkYI = {"Desktop":{"point":"0","unit":"px"}};var bottomlrIkYI = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-RKUOwQ","title":"Kids Friendly","titleTag":"h3","description":"Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit","icon":"gtn gtn-school-light","iconSize":{"Desktop":"70","Tablet":"45"},"align":{"Desktop":"flex-start","Mobile":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[],"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconColor":{"r":233,"g":143,"b":80,"a":1},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[]},"titleMargin":{"Desktop":[]},"titleColor":{"r":58,"g":58,"b":74,"a":1},"titleTypography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":[]},"descColor":{"r":120,"g":120,"b":120,"a":1},"descTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
			<div class="guten-element guten-RKUOwQ guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-school-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Kids Friendly</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.33},"elementId":"guten-pUx1gP","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"700"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-pUx1gP animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="pUx1gP"><script>var toppUx1gP = {"Desktop":{"point":"0","unit":"px"}};var bottompUx1gP = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-Ws6mhc","title":"Mall & Entertai","titleTag":"h3","description":"Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit","icon":"gtn gtn-shopping-cart2-light","iconSize":{"Desktop":"70","Tablet":"45"},"align":{"Desktop":"flex-start","Mobile":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[],"Tablet":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconColor":{"r":233,"g":143,"b":80,"a":1},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[]},"titleMargin":{"Desktop":[]},"titleColor":{"r":58,"g":58,"b":74,"a":1},"titleTypography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":[]},"descColor":{"r":120,"g":120,"b":120,"a":1},"descTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""}} -->
			<div class="guten-element guten-Ws6mhc guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-shopping-cart2-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Mall & Entertai</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
