<?php
/**
 * Gutenverse Services Benefits content.
 */
return array(
	'title'      => __( 'Gutenverse Services Benefits', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-phucwG","background":{"type":"default","image":{"Desktop":{"id":143,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/architecture-structure-white-texture-floor-wall.webp"}},"position":{"Desktop":"center center"},"size":{"Desktop":"contain","Mobile":"custom"},"repeat":{"Desktop":"repeat","Mobile":"repeat"}},"backgroundOverlay":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"opacity":"0.2","margin":{"Desktop":{},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"0","bottom":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20","top":"60","bottom":"20"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"","left":""}}}} -->
			<div class="section-wrapper" data-id="phucwG"><script>var topphucwG = {"Desktop":{"point":"0","unit":"px"}};var bottomphucwG = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-phucwG layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-vDd6Yf","horizontalAlign":{"Desktop":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-vDd6Yf"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="vDd6Yf"><script>var topvDd6Yf = {"Desktop":{"point":"0","unit":"px"}};var bottomvDd6Yf = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-SbXRBr","type":5,"textAlign":{"Desktop":"left"},"color":{"r":233,"g":143,"b":80,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","transform":"uppercase","spacing":{"Desktop":"0.1"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"300"}} -->
			<h5 class="wp-block-gutenverse-heading guten-element guten-SbXRBr animated guten-element-hide desktop-fadeInLeft">Our Benefits</h5>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/heading {"elementId":"guten-7XSY9p","textAlign":{"Desktop":"left"},"color":{"r":58,"g":58,"b":74,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-7XSY9p animated guten-element-hide desktop-fadeInLeft">The Benefits</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-Si6RDk","alignment":{"Desktop":"left"},"textColor":{"r":120,"g":120,"b":120,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"55","left":"","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"200","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
			<div class="guten-element gutenverse-text-editor guten-Si6RDk animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque ullamcorper.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-sXfPmY","animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
			<div class="section-wrapper" data-id="sXfPmY"><script>var topsXfPmY = {"Desktop":{"point":"0","unit":"px"}};var bottomsXfPmY = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-sXfPmY layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-fKhp33","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"300"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-fKhp33 animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="fKhp33"><script>var topfKhp33 = {"Desktop":{"point":"0","unit":"px"}};var bottomfKhp33 = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-KjAbux","title":"Good Traffic","titleTag":"h3","description":"Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit","icon":"gtn gtn-car-2-light","iconSize":{"Desktop":"70","Tablet":"50"},"align":{"Desktop":"flex-start","Mobile":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"80","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20","right":"30","bottom":"20","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconColor":{"r":233,"g":143,"b":80,"a":1},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":58,"g":58,"b":74,"a":1},"titleTypography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"descColor":{"r":120,"g":120,"b":120,"a":1},"descTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"none"}}} -->
			<div class="guten-element guten-KjAbux guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-car-2-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Good Traffic</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-lrIkYI","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"500"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-lrIkYI animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="lrIkYI"><script>var toplrIkYI = {"Desktop":{"point":"0","unit":"px"}};var bottomlrIkYI = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-RKUOwQ","title":"Kids Friendly","titleTag":"h3","description":"Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit","icon":"gtn gtn-school-light","iconSize":{"Desktop":"70","Tablet":"50"},"align":{"Desktop":"flex-start","Mobile":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconColor":{"r":233,"g":143,"b":80,"a":1},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":58,"g":58,"b":74,"a":1},"titleTypography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"descColor":{"r":120,"g":120,"b":120,"a":1},"descTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Tablet":[]}} -->
			<div class="guten-element guten-RKUOwQ guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-school-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Kids Friendly</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-pUx1gP","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"20"}},"Desktop":{}},"padding":{"Mobile":[],"Desktop":{}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"700"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-pUx1gP animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="pUx1gP"><script>var toppUx1gP = {"Desktop":{"point":"0","unit":"px"}};var bottompUx1gP = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-Ws6mhc","title":"Mall & Entertainment","titleTag":"h3","description":"Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit","icon":"gtn gtn-shopping-cart2-light","iconSize":{"Desktop":"70","Tablet":"50"},"align":{"Desktop":"flex-start","Mobile":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconColor":{"r":233,"g":143,"b":80,"a":1},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":58,"g":58,"b":74,"a":1},"titleTypography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"descColor":{"r":120,"g":120,"b":120,"a":1},"descTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Tablet":[]}} -->
			<div class="guten-element guten-Ws6mhc guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-shopping-cart2-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Mall & Entertainment</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->

			<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-rpq1Si","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"100"}} -->
			<div class="section-wrapper" data-id="rpq1Si"><script>var toprpq1Si = {"Desktop":{"point":"0","unit":"px"}};var bottomrpq1Si = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-rpq1Si animated guten-element-hide desktop-fadeInUp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null,"Mobile":null},"elementId":"guten-niUtEj","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"900"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-niUtEj animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="niUtEj"><script>var topniUtEj = {"Desktop":{"point":"0","unit":"px"}};var bottomniUtEj = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-BmfN8t","title":"Green Space","titleTag":"h3","description":"Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit","icon":"gtn gtn-Leaf-light","iconSize":{"Desktop":"70","Tablet":"50"},"align":{"Desktop":"flex-start","Mobile":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"80","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconColor":{"r":233,"g":143,"b":80,"a":1},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":58,"g":58,"b":74,"a":1},"titleTypography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"descColor":{"r":120,"g":120,"b":120,"a":1},"descTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Tablet":[]}} -->
			<div class="guten-element guten-BmfN8t guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-Leaf-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Green Space</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Tablet":null,"Mobile":null},"elementId":"guten-HyOvCA","margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1100"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-HyOvCA animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="HyOvCA"><script>var topHyOvCA = {"Desktop":{"point":"0","unit":"px"}};var bottomHyOvCA = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-kBguJc","title":"Family Oriented","titleTag":"h3","description":"Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit","icon":"gtn gtn-Safe-house-light","iconSize":{"Desktop":"70","Tablet":"50"},"align":{"Desktop":"flex-start","Mobile":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"30"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconColor":{"r":233,"g":143,"b":80,"a":1},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":58,"g":58,"b":74,"a":1},"titleTypography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"descColor":{"r":120,"g":120,"b":120,"a":1},"descTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Tablet":[]}} -->
			<div class="guten-element guten-kBguJc guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-Safe-house-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Family Oriented</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-9Xfz8g","margin":{"Mobile":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"1300"}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-9Xfz8g animated guten-element-hide desktop-fadeInUp"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="9Xfz8g"><script>var top9Xfz8g = {"Desktop":{"point":"0","unit":"px"}};var bottom9Xfz8g = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/icon-box {"elementId":"guten-dEnrwX","title":"Near Hospital","titleTag":"h3","description":"Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit","icon":"gtn gtn-hospital-light","iconSize":{"Desktop":"70","Tablet":"50"},"align":{"Desktop":"flex-start","Mobile":"center"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":[]},"iconMargin":{"Desktop":[]},"iconColor":{"r":233,"g":143,"b":80,"a":1},"iconBorder":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[],"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"r":58,"g":58,"b":74,"a":1},"titleTypography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"}},"weight":"600"},"descMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"descColor":{"r":120,"g":120,"b":120,"a":1},"descTypography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
			<div class="guten-element guten-dEnrwX guten-icon-box icon-position-undefined"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon style-color"><i class="gtn gtn-hospital-light"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Near Hospital</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, Phasel consectetur adipiscing elit. males neque sed pellentesque elit</p></div></div></div>
			<!-- /wp:gutenverse/icon-box --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
