<?php
/**
 * Gutenverse Home CTA content.
 */
return array(
	'title'      => __( 'Gutenverse Home CTA', 'restance' ),
	'categories' => array( 'restance-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"elementId":"guten-xtGsfJ","background":{"type":"default","image":{"Desktop":{"id":1336,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/architecture-villa-house-home-pool-italy-599833-pxhere.com.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":"","width":{"Desktop":{"unit":"%","point":"150"}},"xposition":{"Desktop":{"point":"0","unit":"px"}},"yposition":{"Desktop":{"point":"-350","unit":"px"}}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":1511,"image":"' . esc_url( RESTANCE_URI ) . 'assets/img/shape-divider-5.webp"}},"position":{"Mobile":"custom","Desktop":"bottom left","Tablet":"custom"},"yposition":{"Mobile":{"point":"550","unit":"px"},"Tablet":{"point":"-80","unit":"px"}},"xposition":{"Mobile":{"point":"1","unit":"px"},"Tablet":{"point":"-150","unit":"px"}},"repeat":{"Mobile":"no-repeat","Desktop":"no-repeat"},"size":{"Tablet":"default","Desktop":"custom"},"width":{"Desktop":{"point":"1500","unit":"px"}},"color":{"r":0,"g":0,"b":0,"a":0.6}},"opacity":"1","topDivider":{"width":{"Mobile":""}},"margin":{"Desktop":{},"Tablet":{},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"150","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"70","right":"20","left":"10","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}}}} -->
			<div class="section-wrapper" data-id="xtGsfJ"><script>var topxtGsfJ = {"Desktop":{"point":"0","unit":"px"}};var bottomxtGsfJ = {"Desktop":{"point":"0","unit":"px"}};</script><section class="wp-block-gutenverse-section guten-element guten-section guten-xtGsfJ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-shape-divider guten-shape-divider-top"></div><div class="guten-shape-divider guten-shape-divider-bottom"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":57.55,"Mobile":null,"Tablet":40},"elementId":"guten-Hw32Qq","hideMobile":true} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-Hw32Qq hide-mobile"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="Hw32Qq"><script>var topHw32Qq = {"Desktop":{"point":"0","unit":"px"}};var bottomHw32Qq = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"></div></div></div>
			<!-- /wp:gutenverse/column -->

			<!-- wp:gutenverse/column {"width":{"Desktop":42.44,"Tablet":60,"Mobile":null},"elementId":"guten-TFlSEG","margin":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}}} -->
			<div class="wp-block-gutenverse-column guten-element guten-column guten-TFlSEG"><div class="guten-background-overlay"></div><div class="sticky-wrapper" data-id="TFlSEG"><script>var topTFlSEG = {"Desktop":{"point":"0","unit":"px"}};var bottomTFlSEG = {"Desktop":{"point":"0","unit":"px"}};</script><div class="guten-column-wrapper"><!-- wp:gutenverse/heading {"elementId":"guten-8qc5n5","textAlign":{"Desktop":"right","Mobile":"left"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Playfair Display","value":"Playfair Display","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"42","unit":"px"},"Mobile":{"point":"42","unit":"px"}},"weight":"600"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"20"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"left":""}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"100"}} -->
			<h2 class="wp-block-gutenverse-heading guten-element guten-8qc5n5 animated guten-element-hide desktop-fadeInRight">The Best Partner to Find New House.</h2>
			<!-- /wp:gutenverse/heading -->

			<!-- wp:gutenverse/text-editor {"elementId":"guten-9mTkQe","alignment":{"Desktop":"right","Mobile":"left"},"textColor":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"point":"24","unit":"px"}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20","top":"","right":"","left":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":{},"Mobile":{"unit":"px","dimension":{"right":"","left":"0"}},"Tablet":{"unit":"%","dimension":{"left":"25"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
			<div class="guten-element gutenverse-text-editor guten-9mTkQe animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus malesuada neque sed pellentesque ullamcorper.</p>
			<!-- /wp:paragraph --></div></div>
			<!-- /wp:gutenverse/text-editor -->

			<!-- wp:gutenverse/button {"elementId":"guten-EKSCh4","content":"Contact Us","alignButton":{"Desktop":"right","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"18","bottom":"18","right":"24","left":"24"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"r":233,"g":143,"b":80,"a":1}},"buttonBackgroundHover":{"type":"default","color":{"r":255,"g":255,"b":255,"a":0}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"solid","width":"1","color":{"r":233,"g":143,"b":80,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"color":{"r":233,"g":143,"b":80,"a":1},"type":"solid","width":"1"}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"transform":"uppercase","weight":"400","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"spacing":{"Desktop":"0.1"}},"hoverTextColor":{"r":233,"g":143,"b":80,"a":1}} -->
			<div class="guten-element guten-button-wrapper guten-EKSCh4"><a class="guten-button animated guten-element-hide desktop-fadeInRight guten-button-sm" href="#"><span>Contact Us</span></a></div>
			<!-- /wp:gutenverse/button --></div></div></div>
			<!-- /wp:gutenverse/column --></div></section></div>
			<!-- /wp:gutenverse/section -->',
);
